### ISSUE TITLE
Add Hibernation to Power Button Tweaks

### ISSUE THREAD

**Issue by sujayv-au** [hereafter/power-start-menu#18]
Would it be possible to add hibernation to the Power Button tweaks? For example, Left Click Power Button to Hibernate. This would be really awesome.

Thank you for this great application in any case.

**Comment by hereafter** [comment]
Sure. Adding to the backlog.
I would need a reliable way to detect if Sleep & Hibernate are supported | Enabled.

**Comment by hereafter** [comment]
First I will add an option "Hibernate" to the selectable list of actions. 

- [x]  Expand service to support "Hibernate" action
- [x]  List the "Hibernate" action in the drop-down list for power button options
- [x]  Update Hibernate icon for the power button
- [x]  ARM64 & 22000 supports
- [x]  MUI

**Comment by hereafter** [comment]
Ready for release
