### ISSUE TITLE
The application does NOT work for non-English verisions of Windows 11

### ISSUE THREAD

**Issue by wforweed** [hereafter/power-start-menu#23]
I can not make it work no matter how much I try. The app looks very cool and useful but It doesn't work for me. I tried running it as admin and still no go. I can browse inside the app but I cannot make it work in my system.

This happens on Windows 11 with certain languages, like German.

**Comment by hereafter** [comment]
Could you please share more details of your PC system.
Like build number 10.0.22000 etc,
or even better could you please arrange a remote session with software like teamviewer

**Comment by frytom** [comment]
I can confirm, that the power start menu isn't working on my machine, too. I tried all solutions (re-running with administrator rights etc.) And second, it can not be uninstalled properly. The power start menu entry in the start menu app list will remain after "uninstalling" through the MS store. I used latest windows 11 pro builds (current 22621.1776) retail and release preview builds). So far, nothing seems to help getting your app working or being uninstalled properly.

**Comment by hereafter** [comment]
I am sure 22621.1776 is supported. Have you modded your system with other tools, like Explorer Patcher or Windhawk, Start11. etc. you could turn off those solutions first to see if they are interferencing.


> The power start menu entry in the start menu app list will remain after "uninstalling" through the MS store.

The uninstall will take some time, wait a minute or so, it will get deleted. If you want the process to go faster, go to Task Manager Stop the "PowerStartMenuService.exe" process.

Please do a clean install/restart, and launch "Power start menu" from "start menu" It should work by now.
If it does not try "Repair" button. Please check in Task Manager, the process "PowerStartMenuService.exe" is running.

Please kindly let me know if it helps.
Or if it's ok for me to do a remote session Via teamviewer?

**Comment by frytom** [comment]
Ok. I did a complete uninstall and after a fresh power start menu install. Again, there is no functionality. And I found out, there is  an active process "PowerStartMenuService.exe" found running in the background, but it seems not to work.
I don't have any other start menu tools installed. I only have used MS powertoys. But I did uninstall them, but again, it doesn't make a difference.
 I'm using an unmodified Win 11 Pro. The only program, which goes deep into the system, is here the installed Process Lasso.

**Comment by hereafter** [comment]
> Ok. I did a complete uninstall and after a fresh power start menu install. Again, there is no functionality. And I found out, there is an active process "PowerStartMenuService.exe" found running in the background, but it seems not to work. I don't have any other start menu tools installed. I only have used MS powertoys. But I did uninstall them, but again, it doesn't make a difference.

At current stage I have not included any logging in the released product.
I am open to remote troubleshooting if you need.

Meanwhile I will try to install Process Lasso to see if it has anything to do with it.

**Comment by frytom** [comment]
Maybe there is an interference with the windows security app. Some programs don't work properly, if core isolation is enabled, which is enabled in my windows 11 system. I have all related security functions enabled within the windows security app.

**Comment by hereafter** [comment]
Does it work when core isolation is disabled?

If you can't turn it off, could u please help me to do a check?
get the process explorer here
https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

Use find 

![image](https://github.com/hereafter/power-start-menu/assets/1483954/71b19cc0-300d-42d4-ad9f-25ba52ffe97e)


Type in "power-start-menu"

![image](https://github.com/hereafter/power-start-menu/assets/1483954/82e2c1b8-ec3b-41e2-b79c-a7dbf1888f0b)

Three entities.

I will check the details on core isolation
I do think my "Devkit" box from Microsoft have that enabled.

**Comment by frytom** [comment]
Ok. The process explorer finds only one entry: PowerStartMenuService.exe. The other two are missing.

The Core Isolation has nothing to do with this bug. I've tested with Core Isolation disabled, no change.

Is the "mess" maybe a permissions thing of having not the rights, your app is depending on?

**Comment by hereafter** [comment]
The "Start menu menu process" "StartMenuExperienceHost.exe" failed to load "power-start-menu.dll" 
It could be that the system is missing some vc runtime dlls.

![image](https://github.com/hereafter/power-start-menu/assets/1483954/f3284f35-d1cb-45bf-a195-0d3b388c9407)

This dependency should by right be resolved and installed by Microsoft Store.
Anyway here is the installer if you found it missing

https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages

Pick the x64 build( I assume you are not running on ARM64 processors)
https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx


I will download the exact build Windows 11 Pro Fresh OS and test with it to see if i could replicate it.

**Comment by hereafter** [comment]
I have installed a fresh OS with said build. It runs as expected.

Do you have any Anti-virus software running? they might aggressively mark "unknown" software as virus and stopped the code from loading? 

![image](https://github.com/hereafter/power-start-menu/assets/1483954/1588ce56-59f1-4a7d-a9e0-697d1e4d49d4)

**Comment by frytom** [comment]
Yesterday, I tried installing the missed VClibs UWP file. I was able installing them via POWERSHELL command, but it didn't help eliminating this bug.
Hello, again, today I installed Windows 11 22621.1776 fresh new and right after Power Start Menu. Again, no functionality with a fresh windows installation.
I'm german, so Power Start Menu will be presented with german text. I suspect, that after all other possible errors can be excluded, this bug must have something to do with the custom language files or setup, which might be (some files aren't having the needed) permission related causing to be nonfunctionally.

I don't use any external AV program, only windows defender unmodified.

Process Explorer (in fresh new installed windows) shows again only one entry: PowerStartMenuService.exe

**Comment by hereafter** [comment]
> Yesterday, I tried installing the missed VClibs UWP file. I was able installing them via POWERSHELL command, but it didn't help eliminating this bug. Hello, again, today I installed Windows 11 22621.1776 fresh new and right after Power Start Menu. Again, no functionality with a fresh windows installation. I'm german, so Power Start Menu will be presented with german text. I suspect, that after all other possible errors can be excluded, this bug must have something to do with the custom language files or setup, which might be (some files aren't having the needed) permission related causing to be nonfunctionally.
> 
> I don't use any external AV program, only windows defender unmodified.
> 
> Process Explorer (in fresh new installed windows) shows again only one entry: PowerStartMenuService.exe

I am able to replicate the issue.
There is a resource name used, which are different from region to region.

I will investigate into finding a consistent way of retrieving it.

A fix is on the way

**Comment by hereafter** [comment]
1.6.60 is in the Store.
Please update to see if it helps

**Comment by hereafter** [comment]
Regression found

**Comment by frytom** [comment]
Thanks for the keys. I tried installing version 1.6.60 yesterday, but it didn't succeed. Sorry to say, still no functionality with a german windows 22621.1778.

I'll have to wait for new Power Start Menu ms-store version being released.

**Comment by hereafter** [comment]
1.6.62 is live in the store, which should have fixed the issue would you please confirm it works.

**Comment by frytom** [comment]
I cannot confirm that it (1.6.62.0) is working. Using my german windows, Power Start Menu is still without any functions. Sorry.

**Comment by hereafter** [comment]
> I cannot confirm that it (1.6.62.0) is working. Using my german windows, Power Start Menu is still without any functions. Sorry.

uninstall Power Start Menu
Please goto File Explorer 
Delete folder "%temp%/powerstartmenu
![image](https://github.com/hereafter/power-start-menu/assets/1483954/ff10bb90-2d2a-4f56-be13-45b032650400)

restart windows
then resintall the power start menu, please 


This is me running on a fresh German OS

![image](https://github.com/hereafter/power-start-menu/assets/1483954/2f2fb46c-550e-4825-8513-a686462e98e4)

**Comment by frytom** [comment]
Thanks. The final command, deleting all temp files and directories, was the missing link. Your app is now working as intended.
