### ISSUE TITLE
Application Not Preventing The 'Recommended' Area From Showing In Start Menu

### ISSUE THREAD

**Issue by Davy49** [hereafter/power-start-menu#25]
I'm currently running the following software On my desktop computer: 

Windows 11 Pro Insider Preview, Version 22H2, O.S. Build 23466.1001, Windows Feature Experience Pack 1000.23466.1001.0
A short time ago I got updated to this new windows insider build, and even though I have the switch in the on position the 'recommended' section of the start menu is now being displayed.

**Comment by hereafter** [comment]
I am able to replicate it seems like a regression for 1.6.60

Related to issue #23

**Comment by Davy49** [comment]
Hello,
Thanks so much for your response, I thought that I might have done something incorrectly on my computer.

**Comment by hereafter** [comment]
1.6.62 is live in the store, which should have fixed the issue would you please confirm it works.

**Comment by Davy49** [comment]
I first went into the windows settings area under apps, I tried repairing the app and then then resetting it, that didn't seem to correct my issue. Then I uninstalled it and reinstalled it and now it seems to be functioning properly. 👍

**Comment by hereafter** [comment]
Glad it helps :)
