### ISSUE TITLE
Searchbox Hidden Regardless of User Choice

### ISSUE THREAD

**Issue by AWarthog** [hereafter/power-start-menu#37]
There is a bug in the latest version of Power Start Menu (1.6.65.0) where the searchbox is always hidden, even if the user chooses to show it. This worked on every previous version as far as I am aware. I've tested this on six different computers and got the same result across the board. Reverting to version 1.6.62.0 and rebooting resolved the issue.
![Screenshot](https://github.com/hereafter/power-start-menu/assets/100887619/061477bf-4258-4597-9eea-ad7c770810d0)

**Comment by hereafter** [comment]
yes, latest patch fixes a minor issue, yet forget to consider this settings.
a fix is on its way.

Thanks for reporting

**Comment by hereafter** [comment]
please lookout for 1.6.66 release.
After update you may need to disable the tweaks then re-enable the tweaks

Let me know if it fixes the issue.

**Comment by AWarthog** [comment]
I can confirm that release 1.6.66 has resolved this issue across all of my devices. Thanks a bunch!
